### ISSUE TITLE
Why the file named "mblbp-detect.cpp" was delete?

### ISSUE THREAD

**Issue by williamtang** [t0nyren/welfare2#5]
Hello, Ren

sorry to trouble you but I have a question that, in your project, the file mblbp-detect.cpp/.h were deleted but the makefile still contained the compile command for mblbp. How could I solve the probelm?

Thanks 

Best,
william

**Comment by t0nyren** [comment]
Hi William,

I removed mblbp-detect since it is a licensed library, and I do not have the right to distribute it anymore. The OpenCV detector works just the same as this one.

I've updated the source codes and makefile. Please pull the newest project.

Regards,
Tony

**Comment by williamtang** [comment]
OK, Tony, I'll retry it. Appreciate what you've done, thanks so much.

william
